import Navbar from "./providers/Components/navbar";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mainContainerNavbar">
          <div>
            <div className="h-[65px] bg-[rgba(22,28,40,1)]  ">
              <div className="topNavbarInner ">
                <h1 className="h-[17px]  leading-[17px]  text-left w-full max-w-screen-lg">
                  FOR PATIENTS
                </h1>

                <h1 className="h-[17px]  leading-[17px]  text-left w-full max-w-screen-lg">
                  FOR PROVIDERS
                </h1>
                <h1 className="h-[17px]  leading-[17px]  text-left w-full max-w-screen-lg">
                  FOR PARTNERS
                </h1>
                <h1 className="h-[17px]  leading-[17px]  text-left w-full max-w-screen-lgt">
                  FOR SHOP
                </h1>
              </div>
            </div>
            <div className="max-h-32px top-25px left-144px">
              <Navbar />
            </div>
            <div className="w-[624px] h-[480px] top-[288.69140625px] left-[125px] rounded-[30px]">
              <h1 className="text-[64px]  leading-[83px];"></h1>
              <h2 hCPFM-ISText></h2>
            </div>
          </div>
        </div>

        {children}
        <div className="bg-gray-100 h-[422px] top-[5978px] flex justify-between">
          <div className="flex mt-9 bg-blue-500 w-[1440px] h-[270px] p-[0px] pr-[88px] pl-[88px]">
          
              {" "}
              {/* Lägg till flex här */}
              <div className=" mt-0 bg-red-400 w-[332px] h-[114.09] p-8">
                <div className=" bg-purple-200 w-[113px] h-[68.09px] ">
                  <Image
                    src="/Mask group.png"
                    alt="Mask Image"
                    width={113}
                    height={68.09}
                  />
                  <div className="w-[332px] h-[22px] bg-blue-300 ">
                    <p className="font-[Poppins,sans-serif] font-normal ">
                      Delivering Better Healthcare Solutions
                    </p>
                  </div>
                </div>
              </div>
              <div className="bg-gray-500 w-[150px] h-[270px]">
                <div className="w-[150px] h-[22px]">
                  <p className="text-[Poppins] font-semibold text-[16px] custom-leading ">
                    NAVIGATION LINKS
                  </p>
                </div>
                <div className="bg-green-100 w-[150px] h-[222px] gap-[18px] text-[Poppins] font-medium text-[16px]">
                  <nav className="bg-green-200">home</nav>
                  <nav>About Us</nav>
                  <nav className="bg-green-300"> Platforms</nav>
                  <nav> Partners</nav>
                </div>
              </div>
            
          </div>
        </div>
      </body>
    </html>
  );
}
